sudo: required
services:
  - docker

before_install:
  - docker build -t gothbarbie/docker-complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gothbarbie/docker-complex npm test -- --coverage

after_success:
  - docker build -t gothbarbie/multi-client ./client
  - docker build -t gothbarbie/multi-nginx ./nginx
  - docker build -t gothbarbie/multi-server ./server
  - docker build -t gothbarbie/multi-worker ./worker
# Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push images to docker hub
  - docker push gothbarbie/multi-client
  - docker push gothbarbie/multi-nginx
  - docker push gothbarbie/multi-server
  - docker push gothbarbie/multi-worker